### ISSUE TITLE
Backport Infoscale recipe changes to 4.9

### ISSUE THREAD

**Issue by Veritasosrb** [openshift-psap/special-resource-operator#115]
PR Infoscale-CSI: resizer and provisioner timeouts - https://github.com/openshift-psap/special-resource-operator/pull/112 which is merged in master; is it possible to make this available on release-4.9 also.

**Comment by bthurber** [comment]
Per @dagrayvid , we will need a BZ created for the backport.  Please link when complete.

**Comment by Veritasosrb** [comment]
Here’s the corresponding BZ https://bugzilla.redhat.com/show_bug.cgi?id=2016632

**Comment by ybettan** [comment]
https://github.com/openshift-psap/special-resource-operator/pull/119

**Comment by ybettan** [comment]
@bthurber Now that https://github.com/openshift-psap/special-resource-operator/pull/119 was merged, I think we can close that issue.

**Comment by Veritasosrb** [comment]
Thanks, Closing this.
