### ISSUE TITLE
Add kernel version information in runtime variable

### ISSUE THREAD

**Issue by reenakabra** [openshift-psap/special-resource-operator#14]
Currently we do store full kernel version in runInfo.KernelVersion. But it includes security patch updates also. Driver container image is unlikely to be changed for those kernel for ex: same image will work for both 4.18.0-193.28.1.el8_2.x86_64 and 4.18.0-193.40.1.el8_2.x86_64 kernel. Can we have a variable that stores a sub-string "4.18.0-193". Pods can use this kernel string to fetch images. 
If it is fine I will make the changes and create a pull request or is there any other way to achieve the same.

**Comment by zvonkok** [comment]
@reenakabra Makes sense. I would suggest we add another runtime variable. Some drivers need the full version some need only a subset.

**Comment by zvonkok** [comment]
@reenakabra #15 should take care of this.

**Comment by reenakabra** [comment]
Thanks @zvonkok
