### ISSUE TITLE
Improve the UX when installing SRO via OLM

### ISSUE THREAD

**Issue by ybettan** [openshift-psap/special-resource-operator#169]
When installing SRO via OLM, OLM installs the NFD dependency but doesn't apply the NFD CR, therefore, the NFD controller is running but the nodes are labeled yet so applying the SRO CR will fail.
The best option will be to find a way to make OLM install the NFD CR as well as the controller but I don't know yet if it is possible by OLM.

[Jira link](https://issues.redhat.com/browse/MGMT-8283)

**Comment by zvonkok** [comment]
This could also be done through SRO, to instantiate NFD with a specific CR. For each special resource, we may have customizations to apply to NFD (NFDs CR exposes the NFD client configuration). 

We added recently a very "powerful" custom label(s) engine to NFD so e.g. if a special resource needs a specific label that is not part of the default set of labels, each special resource may update/patch the NFD CR to have the right labels available.

**Comment by ybettan** [comment]
Thanks for you comment @zvonkok.

The current plan is to initiate a default NFD CR before failing on missing labels.

I will dig more into it when I reach to it.

**Comment by bthurber** [comment]
@ybettan any updates on this?

**Comment by ybettan** [comment]
SRO is currently having some design discussions and potential changes.
Will address this issue once we have a "stable" SRO codebase if that's OK @bthurber.

**Comment by bthurber** [comment]
> 

Ack.

**Comment by ybettan** [comment]
SRO 2.0 is using NFD as a soft dependency and NFD will need to be installed manually if needed for SRO use case.
Therefore, there is not need to track this issue anymore. 

Closing it.
