### ISSUE TITLE
OS upgrades

### ISSUE THREAD

**Issue by reenakabra** [openshift-psap/special-resource-operator#29]
How can builds through driver-container-base help in case of OS upgrades? With RHCOS worker nodes, cluster version update will trigger OS upgrade. This can be a minor kernel version update, which is done in rolling way. driver-container-base pod runs on one node. If that node is last to update it will not trigger build for new kernel version. Driver container pods will not come up on nodes that have updated kernel as it will not have image to use or rather it will use old image and fail to load modules. This will create a window where application is down.
Same is true for pre-created images. To identify the correct image to use we can make use of runtime variable .OperatingSystemMajor. But this variable will also take value of last node in list. Which will again get down the application during upgrades. If the old image that was used before upgrade do not have support for new OS, module load will fail with that image. It needs to pick the correct image which can only be done after all the nodes are upgraded and runtime variable .OperatingSystemMajor is changed.
Is my understanding correct?

**Comment by zvonkok** [comment]
@reenakabra The driver-container-base will be extracted and made available upfront. 

We're planning to build this container in an extra pipeline so when an update is available we plan to have this container also available. 

To be more exact the rolling update is per MachineConfigPool and if the pool is not paused. Per default, OpenShift has two MCPs a master and worker pool. After all, operators are updated and are signalling `Upgradeable=true` then and only then the MCO will try to apply the new OS image. 

To make sure that a driver is upgradeable SRO will have preflight checks for testing out the new kernel that is coming with the update. This is one part of having the application always up. 

The second part is the rolling update of nodes in an MCP. The new driver-container-base images that will be externally available but part of the OpenShift release will have the right kernels already baked in. 

To guarantee that the application stays always up, we're currently adding support or a rolling update where we have minimal application downtime. 

The current way would wait until all the nodes are updated, NFD would label the new nodes with the new kernel and SRO would pick them up and apply them to the DS and hence all the needed parts would be rebuilt and restarted. 

/cc @dagrayvid

**Comment by reenakabra** [comment]
Thanks for the detailed explanation.

In current way worker nodes update in rolling way. When node comes up with updated kernel image it will try to use the old image as the kernelVersion environment variable will still point to old kernel. Only when all the nodes are updated we will be able to use new image. So now in this case if old kernel image is not compatible with new kernel version, driver container modules will not load. 

Is there any design document on how are we planning to support rolling upgrade that I can refer? Also by when will be this change available?

**Comment by zvonkok** [comment]
@reenakabra PTAL at the new chapter about rolling updates in OpenShift https://github.com/openshift/enhancements/pull/357 and the PR https://github.com/openshift-psap/special-resource-operator/pull/33

**Comment by reenakabra** [comment]
@zvonkok Thanks for sharing the changes. I went through those changes and have couple of more queries.

In future if we plan to extend the support of SRO on oracle linux or suse, won't it be good to use OperatingSystemMajorMinor instead of OperatingSystemDecimal? Considering oraclelinux is aligned to redhat release they might have same decimal value but the baseOS will be different. In case of prebuild images "rhel8.2" can be a distinguishing factor as to which image to use instead of "8.2".

Currently I am pushing my images in local registry and doing deployment. In case of cluster upgrade it complains as the changes of local registry are not expected. Is there any other way we can test the OS upgrade?

Is it possible to run multiple instances of special resource on different set of nodes in same openshift cluster? Say if I have a 16 worker nodes and i want to run one instance on first 8 nodes and 2nd instance on remaining 8 nodes how can that be done with single SRO running?

**Comment by zvonkok** [comment]
@reenakabra Are you referring to nodeUpdateInfo or the image for the driver-container? For the driver-container are you looking into something like this: 
```
RHEL.  .../kmod-rhel8.2-driver
SUSE   .../kmod-suse10.2-driver
ORACLE .../kmod-oracle8.2-driver 
```
What is the exact error for ` complains as the changes of local registry are not expected` I am not sure what you mean by that. 

Currently, SRO watches all namespaces and can handle several special resources at the same time. What is exactly the use-case? 

Only one instance of SRO with several different special resources works for now. 

How would your setup with different instances of SRO look like? Can this be resolved with different recipes? What would be the difference between  the nodepools?

**Comment by reenakabra** [comment]
@zvonkok I was referring to nodeUpgradeVersion.rhelVersion. But yes my use case is to have some environment variable available that I can use for image name. 
Say my image is something like kmod-{{.OperatingSystemDecimal }}-driver

With rolling upgrade changes, for daemonset X image will be kmod-8.2-driver and 
                                                  daemonset Y it will be kmod-8.3-dirver
if we are upgrading from OCP4.6 to 4.7.

I was proposing if we can use OperatingSystemMajorMinor instead of OperatingSystemDecimal so that image name can be of form: kmod-rhel8.2-driver. With current changes OperatingSystemDecimal  is updated for new daemonset in createFromYAML() and OperatingSystemMajorMinor still has old value.
line 307:        			runInfo.OperatingSystemDecimal = version.rhelVersion

Currently multiple special resources can run at the same time. But consider the case i have 16 worker nodes, i label 8 nodes with label cluster1 and remaining 8 nodes with label cluster2. One special resource instance can manage one set either nodes with label cluster1 or the ones with label cluster2. I want 2 instances of resource running so that both the set of nodes are managed separately. Both the instances can use same set of manifest from the recipe. Just the node selector will vary based on CR. 
Is it possible to have 2 special resources of same recipe running?

**Comment by zvonkok** [comment]
@reenakabra Ah good catch, will add the OperatingSystemMajorMinor to the upgrade info struct in hindsight that we want to support other OSes. I need the decimal represenstation in the case of RHCOS, CentOS, Oracle. 

>Is it possible to have 2 special resources of same recipe running? 

If we're assuming that we want to run each special-resource in its own namespace then running the operator multiple times could be "complex". For running several SROs I would need to switch to a namespaced version where SRO can watch a single or multiple namespaces but these need to be there on startup. I am not able to watch arbitrarily created namespaces that I want so I can create special resources in its own namespace.  Having SRO cluster-wide means all namespaces are watched and two instances would fight each other. Long story short, I will take a deep look into the framework and see if we can make this "work". 

Can you tell me what the difference would be between those two subclusters? Do you want to run different the same recipe e.g. with a different configuration?

**Comment by reenakabra** [comment]
@zvonkok One SRO can be running for the entire cluster. We want 2 instances of special resource recipe running. Difference between them would be of configuration. 1st instance create pods on nodes with selector X and 2nd instance will create pods on nodes with selector Y. Apart from selector I don't think there would be any change in those 2.

**Comment by zvonkok** [comment]
@reenakabra Ah ok great, I see I have it in the CR spec, but need the injection into the objects... Will create an PR to address this. 

`spec.node.selector: "feature.../pci-<VENDOR_ID>.present"` Or any other label you wish to use.

**Comment by zvonkok** [comment]
@reenakabra Going forward with the multi os support I see the best field to use is the                     `feature.node.kubernetes.io/system-os_release.ID`. On RHCOS we will have
```
cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="47.82.202010270142-0"
VERSION_ID="4.7"
OPENSHIFT_VERSION="4.7"
RHEL_VERSION="8.2"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 47.82.202010270142-0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.7"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.7"
OSTREE_VERSION='47.82.202010270142-0'
```
On SUSE

```
# cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"
```
and on Oracle

```
NAME="Oracle Linux Server"
VERSION="8.3"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.3"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:3:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.3
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.3
```

RHCOS -> rhcos
SUSE -> sles
Oracle -> ol 


WDYT?

**Comment by reenakabra** [comment]
@zvonkok I think it should be a combination of "feature.node.kubernetes.io/system-os_release.ID" and "feature.node.kubernetes.io/system-os_release.VERSION_ID". We should also convert rhcos output to rhel format like we do in renderOperatingSystem() so that the behavior is consistent.

We will have some selector like "spec.node.selector: "feature.../is-cluster" which will have the value as "cluster1" for 1st instance and "cluster2" for 2nd instance. Node that are labelled with value cluster1 will be part of 1st instance and likewise node that are labelled "cluster2" will be part of 2nd instance.

**Comment by zvonkok** [comment]
@reenakabra What about making the node.selector an array, so one could provide several labels? 
In your use-case do we need also a node.selector for the DriverContainer? 

The high level spec.node.selector would be injected automatically to all objects that are created with this special resource. 
To fine tune placement of the driver-container we could have spec.driverContainer.node.selector e.g. in the "cluster1". Does this makes sense? 

In the case of RHCOS, VERSION_ID is the same as ClusterVersionMajorMinor, as you said we need to convert that into
the right representation

```
RHCOS:  ID + RHEL_VERSION = rhel8.3
SUSE:   ID + VERSION_ID   = sles15.2
ORACLE: ID + VERSION_ID   = ol8.3
```

**Comment by reenakabra** [comment]
@zvonkok What are the pre-flight checks done for pre-built image? Will it verify if the kernel modules are loaded on new OS or it will just check if the image is available for the new OS version?

In our use case we don't need node selector only for DriverContainer we may have to use the node selector for other container which do not have kernel modules. 

If I understand the approach correctly, we will have a list in node selector where we will specify multiple values for a single label and the controller will check if the yaml is using this label it will create as many resources as there are entries in the label array. 
For example IS-label: cluster1
                                cluster2
I am using this label in node selector in a daemonset so the controller will create 2 daemonset one will have nodeselector IS-label: cluster1 and other will have  nodeselector IS-label: cluster2

There was one more query regarding SRO upgrade, if the SRO is upgraded and the new image have new states added or if the number of the existing state changed for already deployed recipe how will that work?

**Comment by zvonkok** [comment]
@reenakabra The preflight check will try to build the kernel modules on the new kernel version. If we can leverage weak updates we will check if kernel kABI changed and the module may fail. To be sure that all things work we should have a nightly test that we can leverage on prereleased versions. 

The recipes are going to be versioned, I have some idea about that but needs some final thoughts will let you know. If you do an upgrade and do not set a new version in the special resource CR nothing will happen. A special resource version should not change by updating the operator. 

Adding more states will result in a new version of the special resource. I will be adding a version field for the special resource. 

Objects that need to be replicated by the list of label values should then leave out the value just keep the key or we introduce a new annotation to signalize to replicate this object to the list of values.

**Comment by zvonkok** [comment]
@reenakabra I also wanted to introduce MachineConfigPools per special resource. The benefit would be that we can pause the nodepool and prevent any updates done by OpenShift. Meaning we can update all other workers, masters and the operators maybe bringing new recipes. Now you could e.g. create a new updated special resource on the updated nodes and test the version without having to change the running MCP.

**Comment by bthurber** [comment]
Closing in favor of:  https://github.com/openshift-psap/special-resource-operator/issues/96
