### ISSUE TITLE
Changes required for support of SRO on k8s

### ISSUE THREAD

**Issue by reenakabra** [openshift-psap/special-resource-operator#38]
In SRO code secret special-resource-operator-tls is created through a service using annotation " service.beta.openshift.io/serving-cert-secret-name: special-resource-operator-tls". This annotation is openshift specific, secret is not created on a k8s cluster using this service.
Due to unavailability of secret pod special-resource-controller-manager is not created as it fails to mount the secret.

**Comment by zvonkok** [comment]
@reenakabra I will start to work on the k8s support. @dagrayvid Something we need to deal with.

**Comment by reenakabra** [comment]
Hi, We tried some hacks to figure out what changes are required for deploying SRO on k8s. Listing them down for more understanding and reference:

1. Need to deploy CRD for service monitor and cluster operator, these are by default present on openshift.
2. Create TLS secret special-resource-operator-tls manually as K8s does not support the annotation used to create Secret through Service
3. On K8s worker nodes, label   node-role.kubernetes.io/worker="" is not present. CacheNodes() call core dumps if node selector is not specified and it has to get list of nodes with worker label.
4. With the recent NFD, label  feature.node.kubernetes.io/system-os_release.RHEL_VERSION="8.2" is not getting set even on the redhat machines. How is this label set? Also, should this label be more generic to work for non-redhat systems too? Currently have set it manually.
5. Some runtime variables that are populated using labels or other info are specific to openshift and not working on K8s like runInfo.ClusterVersion, runInfo.ClusterVersionMajorMinor, runInfo.ClusterUpgradeInfo, runInfo.PushSecretName, runInfo.OSImageURL, runInfo.Proxy

**Comment by laxmikant-patil** [comment]
@zvonkok @dagrayvid Any further updates on this issue?

**Comment by dagrayvid** [comment]
@laxmikant-patil [This PR](https://github.com/openshift-psap/special-resource-operator/pull/52) has the changes needed to run SRO on vanilla k8s. Please feel free to try it out. We hope to merge it this week after some review.

**Comment by reenakabra** [comment]
Deployment works fine on K8s without any additional dependencies. Closing this issue. Thanks @dagrayvid
