### ISSUE TITLE
Namespace ownership

### ISSUE THREAD

**Issue by reenakabra** [openshift-psap/special-resource-operator#50]
Hi, there is a use case where we want to use same namespace for SR instance and other resources. SRO tries to create the namespace and is fine if the namespace already exists. But along with that it also sets the controller reference on the namespace. This namespace is deleted when the SR instance is deleted. 

According to my understanding, if the other operator already sets controller reference SRO will fail to deploy the SR recipe due to error in SetControllerReference()

Is it possible or rather correct to set controller reference on namespace if it is created by SRO. If it is pre-created can be skip setting reference. Or is there any other way through which we can make sure the namespace is not deleted with the instance if there are other resources present?

**Comment by zvonkok** [comment]
`SetControllerReference` will only fail if there is already an owner, SRO will warn about the ownership and not fail anymore, so creating the NS should be done with #45
