### ISSUE TITLE
Certificate creation with helm support 

### ISSUE THREAD

**Issue by akankshapanse** [openshift-psap/special-resource-operator#53]
With helm support changes in SRO, we observed another issue in context of "Certificate" resource creation through chart templates.
It is seen that "Certificate" resources in template state files are not getting created when the corresponding state executes. Along with the certificate, the associated secret is also not created.
We have not seen this issue with recipe implementation earlier.

Setup details:
OCP version : 4.6.6 (client), 4.6.8(server)
Cert Manager version : 1.3.0

**Comment by zvonkok** [comment]
Fixed by #63
