### ISSUE TITLE
Extra RBAC permissions needed for fencing deployment

### ISSUE THREAD

**Issue by trishnendu** [openshift-psap/special-resource-operator#56]
We are facing some RBAC permission errors while deploying fencing component with SRO. We need the following RBAC permissions in SRO

{APIGroups:[""], Resources:["nodes/finalizers"], Verbs:["update"]}
{APIGroups:[""], Resources:["nodes/status"], Verbs:["update" "patch"]}
{APIGroups:[""], Resources:["pods"], Verbs:["deletecollection"]}
{APIGroups:[""], Resources:["podtemplates"], Verbs:["list" "watch" "get”,”create”,”update”]}
{APIGroups:[""], Resources:["podtemplates/finalizers"], Verbs:["update"]}
{APIGroups:["batch"], Resources:["jobs"], Verbs:["list" "watch" "get" "create" "update" "patch" "delete"]}
{APIGroups:["extensions"], Resources:["jobs"], Verbs:["list" "watch" "get" "create" "update" "patch" "delete"]}

**Comment by zvonkok** [comment]
Fixed by #63
