### ISSUE TITLE
Timeline for pre-flight checks during OCP version upgrade

### ISSUE THREAD

**Issue by akankshapanse** [openshift-psap/special-resource-operator#96]
Looking for pre-flight checks to be implemented at SRO for upgrade functionality as described below:

When the OCP cluster is upgraded and the kernel version supported by new version changes, pre-flight checks, implemented at SRO, will make sure the driver container images for the new kernel version are available before allowing update to proceed. In case the images for new kernel version are not available or the kernel modules for driver container do not load on newer version, SRO will pause the upgrade till the new kernel version supported images are made available, in order to ensure that driver containers are up and running ,without any disruption.

Kindly let us know the timelines with respect to these changes.

**Comment by bthurber** [comment]
FYI we are discussing this as part of enhancing upgrades with SRO.  Plan it to pick this up next quarter once we are done with the design around it.

**Comment by reenakabra** [comment]
For infoscale special resource that uses pre built images, pre-flight check should check if the image is present for the new kernel. Driver container image name has tag 
infoscale_version-OSmajorminor-full_kernelversion

Infoscale version can be checked from infoscale-vtas special resource runargs. OSmajorminor and kernel version would be new OS and kernel values after upgrade. In one of the calls with RedHat we discussed that for driver container pod images can be pulled or built and a pod can be created using the image on a free machine from the machine config pool to verify modules will load after upgrade. In case of issues, SRO will pause the OS upgrade by marking the upgradeable to false during cluster operator upgrade. This will pause the OCP upgrade. Admin can contact respective vendor for the new kernel support.

**Comment by bthurber** [comment]
This will be a new CR to be run prior to upgrades and will be shipped int he OCP 4.11 release.
